apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gwas-depo-logs
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
            storage: 1Gi
  
