apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:xenial
        imagePullPolicy: Always
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
           claimName: gwas-depo-mongo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
