apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gwas-depo-mongo
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
            storage: 50Gi
  
